=== BBN-E/nlplingo/nlplingo/oregon/event_models/uoregon/tools/better_scorer/config/bpjson-schema-v9.json
{ "$schema":     "http://json-schema.org/schema#",
  "$id":         "http://mitre.org/schemas/better/bpjson-schema-v9.json",
  "title":       "BPJSON",
  "description": "BETTER Program JSON Schema, Version 9, as of December 12, 2019; updated with heads January 27, 2020",
  "$comment":    "Updated BPJSON schema to aid in validating BPJSON from multiple sources",
  "definitions": {

      "span": {
          "type": "object",
          "required":     ["string"],
          "properties":   {
              "string":   {"type": "string"},
              "start":    {"type": "integer"},
              "end":      {"type": "integer"},
              "hstring":  {"type": "string"},
              "hstart":   {"type": "integer"},
              "hend":     {"type": "integer"},
	      "no-head":  {"type": "boolean"},
              "synclass": {"type": "string", "enum": ["Name", "Nominal", "Pronoun", "NotEntity-NotEvent", "Event-Anchor"]}}},

      "spanset": {
          "type":       "object",
          "required":   ["spans"],
          "additionalProperties": false,
          "properties": {
              "ssid":  {"type": "string"},
              "spans": {"type": "array", "items": {"$ref": "#/definitions/span"}}}},

      "provenance":
         {"type": "object",
          "properties":
              {"annotation-date":        {"type": "string"},
               "annotation-procedure":   {"type": "string", "enum": ["pretagger", "mturk", "mat"]},
               "annotator-class":        {"type": "string", "enum": ["crowd", "mitre", "system", "pretagger"]},
               "annotator-id":           {"type": "string"},
               "annotations-role":       {"type": "string", "enum": ["reference", "system"]},
               "hit-id":                 {"type": "string"},
               "worker-id":              {"type": "string"},
               "corpus-id":              {"type": "string"},
               "corpus-creation-date":   {"type": "string"},
               "source":                 {"type": "string"},
               "validations":            {"type": "object",
                                          "propertyNames":        {"type": "string"},
                                          "additionalProperties": {"type": "string", "enum": ["yes", "no"]}},
               "naive-bayes":            {"type": "object",
                                          "properties": {"answer": {"type": "string", "enum": ["yes", "no"]},
                                                         "score":  {"type": "number"}}},
               "revalidations":          {"type": "object",
                                          "propertyNames":        {"type": "string"},
                                          "additionalProperties": {"type": "string", "enum": ["yes", "no"]}},
               "quadclass-mv-judgments": {"type": "object",
                                          "propertyNames":        {"type": "string"},
                                          "additionalProperties": {"type": "string", "enum": ["yes", "no"]}},
               "quadclass-hh-judgments": {"type": "object",
                                          "propertyNames":        {"type": "string"},
                                          "additionalProperties": {"type": "string", "enum": ["yes", "no"]}},
               "event-in-xml":           {"type": "string"}}},

      "abstract-event": {
          "type": "object",
          "required":   ["agents", "patients", "anchors", "helpful-harmful", "material-verbal"],
          "additionalProperties": false,
          "properties": {
              "eventid":         {"type": "string"},
              "helpful-harmful": {"type": "string", "enum": ["helpful", "harmful", "neutral"]},
              "material-verbal": {"type": "string", "enum": ["material", "verbal", "both", "unk"]},
              "agents":          {"type": "array", "items": {"type": "string"}},
              "patients":        {"type": "array", "items": {"type": "string"}},
              "anchors":         {"type": "string"},
              "valid":           {"type": "string", "enum": ["true", "false"]},
              "provenance":      {"$ref": "#/definitions/provenance"}}},

      "annotation-set":
         {"type": "object",
          "additionalProperties": false,
          "required":   ["abstract-events"],
          "properties":
              {"abstract-events": 
                 {"type": "object",
                  "required": ["events", "span-sets"],
                  "properties":
                      {"events":   {"type":                 "object",
                                    "propertyNames":        {"type": "string"},
                                    "additionalProperties": {"$ref": "#/definitions/abstract-event"}}},
                      "span-sets": {"type":                 "object",
                                    "propertyNames":        {"type": "string"},
                                    "additionalProperties": {"$ref": "#/definitions/spanset"}},
                      "directional-coref": {"type":                 "object",
                                            "propertyNames":        {"type": "string"},
                                            "additionalProperties": {"type": "array", "items": {"type": "array", "items": {"type": "string"}}}}}}},

      "entry":
         {"type": "object",
          "additionalProperties": false,
          "required":   ["entry-id"],
          "properties": {
              "entry-id":        {"type": "string"},
              "doc-id":          {"type": "string"},
              "sent-id":         {"type": "string"},
              "provenance":      {"$ref": "#/definitions/provenance"},
              "segment-type":    {"type": "string", "enum": ["sentence", "document"]},
	      "segment-text":    {"type": "string"},
	      "start-in-source": {"type": "number"},
	      "end-in-source":   {"type": "number"},
	      "segment-start":   {"type": "number"},
	      "segment-end":     {"type": "number"},
	      "source-type":     {"type": "string"},
              "annotation-sets": {"$ref": "#/definitions/annotation-set"}}}
  },

  "type":       "object",
  "required":   ["format-type", "format-version", "corpus-id", "entries"],
  "properties":
     {"format-type":      {"type": "string", "enum": ["bp-corpus"]},
      "format-version":   {"type": "string", "enum": ["v8f", "v9"]},
      "corpus-id":        {"type": "string"},
      "annotations-role": {"type": "string", "enum": ["reference", "system"]},
      "annotator-type":   {"type": "string", "enum": ["mturk", "mitre", "system", "pretagger-v1"]},
      "annotator-id":     {"type": "string"},
      "hit-id":           {"type": "string"},
      "entries":          {"type":                 "object",
                           "propertyNames":        {"type": "string"},
                           "additionalProperties": {"$ref": "#/definitions/entry"}}}
}

=== BBN-E/nlplingo/nlplingo/oregon/event_models/uoregon/tools/better_scorer/sampledata/t8.v0.ref.bp.json
{
  "corpus-id": "abstract-t8-1",
  "entries": {
    "doc-0_12_0": {
      "annotation-sets": {
        "abstract-events": {
          "events": {
            "event1": {
              "agents": [
                "ss-4"
              ],
              "anchors": "ss-3",
              "eventid": "event1",
              "helpful-harmful": "harmful",
              "material-verbal": "material",
              "patients": [
                "ss-2"
              ]
            },
            "event2": {
              "agents": [
                "ss-2"
              ],
              "anchors": "ss-1",
              "eventid": "event2",
              "helpful-harmful": "neutral",
              "material-verbal": "material",
              "patients": [
                "ss-2"
              ]
            }
          },
          "span-sets": {
            "ss-1": {
              "spans": [
                {
                  "hstring": "pull away",
                  "string": "pull away"
                }
              ],
              "ssid": "ss-1"
            },
            "ss-2": {
              "spans": [
                {
                  "hstring": "bus",
                  "string": "a bus"
                }
              ],
              "ssid": "ss-2"
            },
            "ss-3": {
              "spans": [
                {
                  "hstring": "closed in",
                  "string": "closed in"
                }
              ],
              "ssid": "ss-3"
            },
            "ss-4": {
              "spans": [
                {
                  "hstring": "mob",
                  "string": "a mob"
                }
              ],
              "ssid": "ss-4"
            }
          }
        }
      },
      "doc-id": "doc-0",
      "entry-id": "doc-0_12_0",
      "segment-text": "On the afternoon of Oct. 7, 1974, a mob of 200 enraged whites, many of them students, closed in on a bus filled with black students that was trying to pull away from the local high school.",
      "segment-type": "sentence",
      "sent-id": "12"
    },
    "doc-0_28_0": {
      "annotation-sets": {
        "abstract-events": {
          "events": {
            "event1": {
              "agents": [],
              "anchors": "ss-10",
              "eventid": "event1",
              "helpful-harmful": "neutral",
              "material-verbal": "material",
              "patients": [
                "ss-11"
              ]
            },
            "event2": {
              "agents": [
                "ss-8"
              ],
              "anchors": "ss-7",
              "eventid": "event2",
              "helpful-harmful": "neutral",
              "material-verbal": "verbal",
              "patients": [
                "ss-9"
              ]
            },
            "event3": {
              "agents": [],
              "anchors": "ss-9",
              "eventid": "event3",
              "helpful-harmful": "harmful",
              "material-verbal": "material",
              "patients": []
            },
            "event4": {
              "agents": [
                "ss-2"
              ],
              "anchors": "ss-1",
              "eventid": "event4",
              "helpful-harmful": "neutral",
              "material-verbal": "verbal",
              "patients": [
                "ss-3"
              ]
            },
            "event5": {
              "agents": [
                "ss-5"
              ],
              "anchors": "ss-4",
              "eventid": "event5",
              "helpful-harmful": "harmful",
              "material-verbal": "material",
              "patients": [
                "ss-6"
              ]
            }
          },
          "span-sets": {
            "ss-1": {
              "spans": [
                {
                  "hstring": "insisted",
                  "string": "insisted"
                }
              ],
              "ssid": "ss-1"
            },
            "ss-10": {
              "spans": [
                {
                  "hstring": "found",
                  "string": "found"
                }
              ],
              "ssid": "ss-10"
            },
            "ss-11": {
              "spans": [
                {
                  "hstring": "weapon",
                  "string": "weapon"
                }
              ],
              "ssid": "ss-11"
            },
            "ss-2": {
              "spans": [
                {
                  "hstring": "driver",
                  "string": "The bus driver"
                }
              ],
              "ssid": "ss-2"
            },
            "ss-3": {
              "spans": [
                {
                  "hstring": "shot",
                  "string": "shot"
                }
              ],
              "ssid": "ss-3"
            },
            "ss-4": {
              "spans": [
                {
                  "hstring": "firing",
                  "string": "firing"
                }
              ],
              "ssid": "ss-4"
            },
            "ss-5": {
              "spans": [
                {
                  "hstring": "someone",
                  "string": "someone"
                }
              ],
              "ssid": "ss-5"
            },
            "ss-6": {
              "spans": [
                {
                  "hstring": "bus",
                  "string": "the bus"
                }
              ],
              "ssid": "ss-6"
            },
            "ss-7": {
              "spans": [
                {
                  "hstring": "indicate",
                  "string": "indicate"
                }
              ],
              "ssid": "ss-7"
            },
            "ss-8": {
              "spans": [
                {
                  "hstring": "evidence",
                  "string": "no evidence"
                }
              ],
              "ssid": "ss-8"
            },
            "ss-9": {
              "spans": [
                {
                  "hstring": "shot",
                  "string": "shot"
                }
              ],
              "ssid": "ss-9"
            }
          }
        }
      },
      "doc-id": "doc-0",
      "entry-id": "doc-0_28_0",
      "segment-text": "No weapon was found, and there was no evidence to indicate that the shot had come from the bus. The bus driver insisted it had not come from the bus, but from someone firing at the bus.",
      "segment-type": "sentence",
      "sent-id": "28"
    },
    "doc-0_47_0": {
      "annotation-sets": {
        "abstract-events": {
          "events": {
            "event1": {
              "agents": [
                "ss-2"
              ],
              "anchors": "ss-6",
              "eventid": "event1",
              "helpful-harmful": "neutral",
              "material-verbal": "material",
              "patients": []
            },
            "event2": {
              "agents": [
                "ss-2"
              ],
              "anchors": "ss-4",
              "eventid": "event2",
              "helpful-harmful": "neutral",
              "material-verbal": "verbal",
              "patients": [
                "ss-5"
              ]
            },
            "event3": {
              "agents": [],
              "anchors": "ss-5",
              "eventid": "event3",
              "helpful-harmful": "harmful",
              "material-verbal": "material",
              "patients": []
            },
            "event4": {
              "agents": [
                "ss-2"
              ],
              "anchors": "ss-1",
              "eventid": "event4",
              "helpful-harmful": "neutral",
              "material-verbal": "verbal",
              "patients": [
                "ss-3"
              ]
            },
            "event5": {
              "agents": [],
              "anchors": "ss-3",
              "eventid": "event5",
              "helpful-harmful": "harmful",
              "material-verbal": "material",
              "patients": []
            }
          },
          "span-sets": {
            "ss-1": {
              "spans": [
                {
                  "hstring": "report",
                  "string": "report"
                }
              ],
              "ssid": "ss-1"
            },
            "ss-2": {
              "spans": [
                {
                  "hstring": "witness",
                  "string": "the main witness"
                }
              ],
              "ssid": "ss-2"
            },
            "ss-3": {
              "spans": [
                {
                  "hstring": "kidnapping",
                  "string": "kidnapping"
                }
              ],
              "ssid": "ss-3"
            },
            "ss-4": {
              "spans": [
                {
                  "hstring": "reporting",
                  "string": "reporting"
                }
              ],
              "ssid": "ss-4"
            },
            "ss-5": {
              "spans": [
                {
                  "hstring": "crimes",
                  "string": "crimes"
                }
              ],
              "ssid": "ss-5"
            },
            "ss-6": {
              "spans": [
                {
                  "hstring": "witness",
                  "string": "witness"
                }
              ],
              "ssid": "ss-6"
            }
          }
        }
      },
      "doc-id": "doc-0",
      "entry-id": "doc-0_47_0",
      "segment-text": "Never mind that the main witness, a former girlfriend of Mr. Tyler's, was a troubled youngster who had been under the care of a psychiatrist and had a history of reporting phony crimes to the police, including a false report of a kidnapping.",
      "segment-type": "sentence",
      "sent-id": "47"
    },
    "doc-0_4_0": {
      "annotation-sets": {
        "abstract-events": {
          "events": {
